# Generated by Django 5.0.1 on 2024-02-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='state',
            field=models.CharField(choices=[('r', 'Request rejected'), ('a', 'Request accepted')], default='x', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='state',
            field=models.CharField(choices=[('r', 'Adopetion requested'), ('a', 'Adopetion accepted')], default='x', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(verbose_name='Age(Days)'),
        ),
    ]
