# Generated by Django 5.0.1 on 2024-02-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_adoptionrequest_state_pet_state_alter_pet_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='state',
            field=models.CharField(choices=[('p', 'Request pending'), ('r', 'Request rejected'), ('a', 'Request accepted')], default='p', max_length=2),
        ),
    ]
