# Generated by Django 5.0.1 on 2024-02-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_alter_adoptionrequest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='state',
            field=models.CharField(choices=[('r', 'Adoption requested'), ('a', 'Adoption accepted')], max_length=2),
        ),
    ]
